In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pickle
import pandas as pd

In [22]:
with open('articles.pkl', 'rb') as fp:
    articles = pickle.load(fp)
print(articles)

{109513: {'clicks': 1389, 'views': 20650, 'features': array([[2.11406e-01],
       [3.60000e-05],
       [2.77300e-03],
       [5.69886e-01],
       [2.15900e-01]]), 'id': 109513, 'probability': 0.06726392251815981}, 109473: {'clicks': 1073, 'views': 24024, 'features': array([[2.95442e-01],
       [1.40000e-05],
       [1.35191e-01],
       [2.92304e-01],
       [2.77050e-01]]), 'id': 109473, 'probability': 0.044663669663669664}, 109506: {'clicks': 740, 'views': 16581, 'features': array([[2.64355e-01],
       [1.20000e-05],
       [3.73930e-02],
       [4.20649e-01],
       [2.77591e-01]]), 'id': 109506, 'probability': 0.04462939509076654}, 109511: {'clicks': 1825, 'views': 31747, 'features': array([[3.81149e-01],
       [1.29000e-04],
       [6.00380e-02],
       [2.69129e-01],
       [2.89554e-01]]), 'id': 109511, 'probability': 0.05748574668472611}, 109505: {'clicks': 18, 'views': 305, 'features': array([[3.75829e-01],
       [2.50000e-05],
       [3.30410e-02],
       [3.49637e-01]

In [26]:
outlier = []
for art in articles.values():
    if len(art['features']) < 6:
        outlier.append(art['id'])
print(outlier)

[[2.11406e-01]
 [3.60000e-05]
 [2.77300e-03]
 [5.69886e-01]
 [2.15900e-01]]
[[2.95442e-01]
 [1.40000e-05]
 [1.35191e-01]
 [2.92304e-01]
 [2.77050e-01]]
[[2.64355e-01]
 [1.20000e-05]
 [3.73930e-02]
 [4.20649e-01]
 [2.77591e-01]]
[[3.81149e-01]
 [1.29000e-04]
 [6.00380e-02]
 [2.69129e-01]
 [2.89554e-01]]
[[3.75829e-01]
 [2.50000e-05]
 [3.30410e-02]
 [3.49637e-01]
 [2.41468e-01]]
[[2.97750e-01]
 [1.30000e-05]
 [1.16030e-02]
 [5.12182e-01]
 [1.78452e-01]]
[[0.249086]
 [0.001009]
 [0.514682]
 [0.067732]
 [0.167491]]
[[4.21669e-01]
 [1.10000e-05]
 [1.09020e-02]
 [3.09585e-01]
 [2.57833e-01]]
[[0.306008]
 [0.00045 ]
 [0.077048]
 [0.230439]
 [0.386055]]
[[2.97322e-01]
 [2.50000e-05]
 [3.49510e-02]
 [4.13566e-01]
 [2.54137e-01]]
[[4.38513e-01]
 [3.00000e-06]
 [3.07140e-02]
 [3.84494e-01]
 [1.46277e-01]]
[[0.306008]
 [0.00045 ]
 [0.077048]
 [0.230439]
 [0.386055]]
[[3.31830e-01]
 [2.20000e-05]
 [1.99040e-02]
 [4.40390e-01]
 [2.07855e-01]]
[[2.87909e-01]
 [2.50000e-05]
 [8.98300e-03]
 [5.11333e-0